# generated by DipDup 8.5.0

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class TokenX(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fa12: str


class Fa2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    token_id: str
    token_address: str


class TokenX1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fa2: Fa2


class TokenY(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fa12: str


class TokenY1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fa2: Fa2


class DeployPoolParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cur_tick_index: str
    token_x: TokenX | TokenX1
    token_y: TokenY | TokenY1
    fee_bps: str
    tick_spacing: str
    extra_slots: str
