# generated by datamodel-codegen:
#   filename:  transfer.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel, RootModel
from pydantic import ConfigDict


class Tx(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )

    to_: str
    token_id: str
    amount: str


class TransferParameterItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    from_: str
    txs: List[Tx]


TransferParameter = RootModel[List[TransferParameterItem]]
