# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, RootModel
from typing import Any, Optional

class Fa2TokenStorage(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )

    root: Any | None = None

