# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict, Any

from pydantic import BaseModel, ConfigDict, RootModel


class Fa12TokenStorage(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )

    root: Any | None = None
