# generated by datamodel-codegen:
#   filename:  transfer.json

from __future__ import annotations
from typing import Union
from pydantic import BaseModel, RootModel, ConfigDict, Field, AliasChoices

class TransferParameter(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    from_: str = Field(..., validation_alias=AliasChoices('from', 'address_0'))
    to: str = Field(..., validation_alias=AliasChoices('to', 'address_1'))
    value: str = Field(..., validation_alias=AliasChoices('value', 'nat'))

