# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class Fa12TokenStorage(BaseModel):
    class Config:
        extra = Extra.ignore
