# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class Fa2TokenStorage(BaseModel):
    class Config:
        extra = Extra.ignore
