# generated by datamodel-codegen:
#   filename:  x_to_y.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict


class XToYParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )

    dx: str
    deadline: str
    min_dy: str
    to_dy: str
    referral_code: Optional[str]
