# generated by datamodel-codegen:
#   filename:  deploy_pool.json

from __future__ import annotations

from typing import Union

from pydantic import BaseModel, Extra


class TokenXItem(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: str


class Fa2(BaseModel):
    class Config:
        extra = Extra.forbid

    token_id: str
    token_address: str


class TokenXItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Fa2


class TokenYItem(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: str


class Fa21(BaseModel):
    class Config:
        extra = Extra.forbid

    token_id: str
    token_address: str


class TokenYItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Fa21


class DeployPoolParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    cur_tick_index: str
    token_x: Union[TokenXItem, TokenXItem1]
    token_y: Union[TokenYItem, TokenYItem1]
    fee_bps: str
    tick_spacing: str
    extra_slots: str
